"""
Django settings for db4_one68 project.

Generated by 'django-admin startproject' using Django 2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
from pathlib import Path

from django.conf.global_settings import DATETIME_INPUT_FORMATS

from django.conf import settings
# from rest_framework.permissions import *
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
# BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE_DIR = Path(__file__).resolve().parent.parent



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '5i@hb-r25g*itt4p&#-)i-g@=x25#kxrerjr0^h#+iot78x@)a'

CKEDITOR_CONFIGS = {
    'default': {
        'height': 150,
        'width': '100%',
        'filebrowserWindowHeight': 725,
        'filebrowserWindowWidth': "100%",
        'toolbarCanCollapse': True,
        # 'mathJaxLib': '//cdn.mathjax.org/mathjax/2.2-latest/MathJax.js?config=TeX-AMS_HTML',
        'tabSpaces': 4,
    }
}


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*','one68-db-env.eba-qsjdjmsz.us-west-2.elasticbeanstalk.com']

# rest_framework:

REST_FRAMEWORK = {
'DEFAULT_PERMISSION_CLASSES': [
'rest_framework.permissions.AllowAny',
#IsAuthenticated',
]
}

# Application definition

INSTALLED_APPS = [
    # 'admin_interface',
    # 'flat_responsive', # only if django version < 2.0
    # 'flat', # only if django version < 1.9
    # 'colorfield',
    'deals.apps.DealsConfig',
    'ckeditor',
    'bootstrap_modal_forms',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    "corsheaders",
    "simple_history",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',
]

ROOT_URLCONF = 'db4_one68.urls'
FILE_UPLOAD_MAX_MEMORY_SIZE = 10000000
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
# DATETIME_INPUT_FORMATS += ('%Y-%m-%d %H:%M:%S.%f','%Y-%m-%dT%H:%M:%S')

DATETIME_INPUT_FORMATS = ['%Y-%m-%d %H:%M:%S',
 '%Y-%m-%d %H:%M:%S.%f',
 '%Y-%m-%d %H:%M',
 '%Y-%m-%d',
 '%Y-%m-%d %H:%M:%S.%f',
 '%Y-%m-%dT%H:%M:%S']

WSGI_APPLICATION = 'db4_one68.wsgi.application'
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10240

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

# if os.environ.get('DB_ENGINE') and os.environ.get('DB_ENGINE') == "mysql":
DATABASES = { 
    'default': {
        'ENGINE'  : 'django.db.backends.mysql', 
        'NAME'    : os.getenv('DB_NAME'     , 'ebdb'),
        'USER'    : os.getenv('DB_USERNAME' , 'admin'),
        'PASSWORD': os.getenv('DB_PASS'     , 'One68global!'),
        'HOST'    : os.getenv('DB_HOST'     , 'awseb-e-2mippw4akb-stack-awsebrdsdatabase-g1ac8vvgezyx.cvvgo4wufb3g.us-west-2.rds.amazonaws.com'),
        'PORT'    : os.getenv('DB_PORT'     , 3306),
    }
 }
# else:
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': 'db.sqlite3',
#         }
#     }
# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Email

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.office365.com'
EMAIL_HOST_USER = 'ygao@one68global.com'
EMAIL_HOST_PASSWORD = 'GL67yf981001'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_USE_SSL = False


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/


LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/New_York'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'


AWS_QUERYSTRING_AUTH = False

AWS_ACCESS_KEY_ID = 'AKIAQI6BFNVFSCBPKS52'

AWS_SECRET_ACCESS_KEY = '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'


AWS_STORAGE_BUCKET_NAME = 'media-saver'

STATIC_ROOT = 'static'
MEDIA_ROOT ='media'
STATIC_URL='/static/'
MEDIA_URL ='/media/'
#new: 
# STATICFILES_DIRS = (
#     os.path.join(BASE_DIR, "static"),
# )
# old: 
# STATICFILES_DIRS = ('static',)
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:8000",
]
# TEMPLATE_DIRS = ('templates',)